# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 519)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/title.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#MainWindow{background-color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton{\n"
"border-style:none;\n"
"text-align: center;\n"
"background-color:#0079b6;\n"
"border:2px;\n"
"border-radius:2px;\n"
"color:#ffffff;\n"
"}\n"
"#pushButton_run,#pushButton_excel,#pushButton_set{\n"
"border-style:none;\n"
"text-align: center;\n"
"background-color:#20b1ff;\n"
"border:2px;\n"
"border-radius:2px;\n"
"color:#ffffff;\n"
"}\n"
"#pushButton_run:hover,#pushButton_excel:hover,#pushButton_set:hover{\n"
"color:lightskyblue\n"
"}\n"
"#pushButton_run:pressed,#pushButton_excel:pressed,#pushButton_set:pressed {\n"
"    /* 改变背景色 */\n"
"    /* background-color:rgb(180, 180, 180,120); */\n"
"    /* 改变边框风格 */\n"
"    /* border-style:inset; */\n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:6px;\n"
"    padding-top:4px;\n"
"}\n"
"#lineEdit_excel{\n"
"border: 1px solid #20b1ff;\n"
"border-radius:2px;\n"
"background-color:#f0f0f0;\n"
"}\n"
"QLineEdit{\n"
"border: 1px solid #20b1ff;\n"
"border-radius:2px;\n"
"background-color:#FFFFFF;\n"
"}\n"
"QDateTimeEdit{\n"
"border: 1px solid #20b1ff;\n"
"border-radius:2px;\n"
"background-color:#FFFFFF;\n"
"}\n"
"#widget,#widget_4{\n"
"border-radius:5px;\n"
"background-color:#eeeeee;\n"
"}\n"
"#widget_2,#widget_6{\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"background-color:#eeeeee;\n"
"}\n"
"#widget_3,#widget_8{\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"background-color:#eeeeee;\n"
"}\n"
"#widget_7,#widget_5{\n"
"background-color:#eeeeee;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_excel = QtWidgets.QPushButton(self.widget)
        self.pushButton_excel.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_excel.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_excel.setFont(font)
        self.pushButton_excel.setObjectName("pushButton_excel")
        self.horizontalLayout.addWidget(self.pushButton_excel)
        self.lineEdit_excel = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_excel.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_excel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_excel.setFont(font)
        self.lineEdit_excel.setText("")
        self.lineEdit_excel.setReadOnly(True)
        self.lineEdit_excel.setObjectName("lineEdit_excel")
        self.horizontalLayout.addWidget(self.lineEdit_excel)
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_1.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_1.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setChecked(False)
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_9.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.lineEdit_s1 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_s1.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_s1.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_s1.setFont(font)
        self.lineEdit_s1.setText("")
        self.lineEdit_s1.setReadOnly(False)
        self.lineEdit_s1.setObjectName("lineEdit_s1")
        self.horizontalLayout_2.addWidget(self.lineEdit_s1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_2.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.lineEdit_s2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s2.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_s2.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_s2.setFont(font)
        self.lineEdit_s2.setText("")
        self.lineEdit_s2.setReadOnly(False)
        self.lineEdit_s2.setObjectName("lineEdit_s2")
        self.horizontalLayout_3.addWidget(self.lineEdit_s2)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_10.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.lineEdit_s3 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_s3.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_s3.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_s3.setFont(font)
        self.lineEdit_s3.setText("")
        self.lineEdit_s3.setReadOnly(False)
        self.lineEdit_s3.setObjectName("lineEdit_s3")
        self.horizontalLayout_3.addWidget(self.lineEdit_s3)
        self.verticalLayout.addWidget(self.widget_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_11.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_11.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_1.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setText("")
        self.lineEdit_1.setReadOnly(False)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_6.addWidget(self.lineEdit_1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_12.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_12.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_4.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_5.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_5.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_7.addWidget(self.lineEdit_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_6.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_7.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.dateTimeEdit_1 = QtWidgets.QDateTimeEdit(self.widget_8)
        self.dateTimeEdit_1.setMinimumSize(QtCore.QSize(150, 25))
        self.dateTimeEdit_1.setMaximumSize(QtCore.QSize(150, 25))
        self.dateTimeEdit_1.setDate(QtCore.QDate(2020, 1, 1))
        self.dateTimeEdit_1.setObjectName("dateTimeEdit_1")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit_1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_8.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_8.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.widget_8)
        self.dateTimeEdit_2.setMinimumSize(QtCore.QSize(150, 25))
        self.dateTimeEdit_2.setMaximumSize(QtCore.QSize(150, 25))
        self.dateTimeEdit_2.setDate(QtCore.QDate(2020, 1, 1))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit_2)
        self.verticalLayout.addWidget(self.widget_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_set = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_set.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_set.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_set.setFont(font)
        self.pushButton_set.setObjectName("pushButton_set")
        self.horizontalLayout_4.addWidget(self.pushButton_set)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_run = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_run.setMinimumSize(QtCore.QSize(120, 25))
        self.pushButton_run.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_4.addWidget(self.pushButton_run)
        self.verticalLayout.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "亚马逊表格处理"))
        self.pushButton_excel.setText(_translate("MainWindow", "导入表格"))
        self.pushButton_1.setText(_translate("MainWindow", "筛选"))
        self.pushButton_9.setText(_translate("MainWindow", "筛选价格"))
        self.pushButton_2.setText(_translate("MainWindow", "筛选物流"))
        self.pushButton_10.setText(_translate("MainWindow", "筛选跟卖"))
        self.pushButton_11.setText(_translate("MainWindow", "物品状况"))
        self.pushButton_12.setText(_translate("MainWindow", "减去价格"))
        self.pushButton_3.setText(_translate("MainWindow", "库存数量"))
        self.pushButton_4.setText(_translate("MainWindow", "发货方式"))
        self.pushButton_5.setText(_translate("MainWindow", "跟卖方式"))
        self.pushButton_6.setText(_translate("MainWindow", "备货周期"))
        self.pushButton_7.setText(_translate("MainWindow", "跟卖时间"))
        self.dateTimeEdit_1.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm"))
        self.pushButton_8.setText(_translate("MainWindow", "下架时间"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm"))
        self.pushButton_set.setText(_translate("MainWindow", "保存设置"))
        self.pushButton_run.setText(_translate("MainWindow", "导    出"))
import img_rc
